name: triggering the repo B

on:
  push:
    branches:
    -  'main'

jobs:
  build:
     runs-on: ubuntu-latest
     steps:
     -  name: this is the triggering the repo B
        run: |
          curl -X POST \
            -H "Authorization: token ${{ secrets.mine }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/yaswanththinkpad/bingo/actions/workflows/main.yml/dispatches \
            -d '{"ref":"main", "inputs": {"branch": "main"}}'
     
