name: CI workflow

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

jobs:
  name: CI process
  build:
    runs-on: ubuntu:latest
    container: python:3.9-slim
    steps:
      uses: actions/checkout@v4
      name: checkout the code
      run: |
        docker build -t myimage:v1 .